security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 
            algorithm: 'auto'
           # algorithm: plaintext   # Per test, non usare in produzione!

    providers:
        users_in_memory:
            memory:
                users:
                    admin: 
                        password: '$2y$13$XuBRiDLFo69lDjWgmRUY/e4fTMRI9Hq6S.RiA98EBeeP2sAh6.ef.'  # Password in chiaro per test
                        roles: ['ROLE_USER']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        api:
            pattern: ^/api
            stateless: true
            provider: users_in_memory
            http_basic:
                realm: Secured Area

    access_control:
        - { path: ^/api, roles: ROLE_USER }